---
- hosts: elk-host
  become: True
  roles:
    - { role: docker, tags: ["docker"] }
    - { role: ufw, tags: ["firewall"] }
    - { role: elasticsearch, tags: ["elastic"] }
    - { role: kibana, tags: ["kibana"] }
