- name: Create kibana user
  user:
    name: kibana
    
- name: Add kibana user to docker group
  user:
    name: kibana
    group: docker
    append: yes

- name: Copy template systemd
  template: src=kibana.service.j2 dest=/etc/systemd/system/kibana.service owner=root group=root mode=0644
  notify: reload systemd

- name: reload systemd
  shell: systemctl daemon-reload
  
- name: restart kibana
  service:
    name: kibana.service
    state: restarted
    enabled: yes
