- name: Create a network
  docker_network:
    name: elastic
    
- name: Create a volume
  docker_volume:
    name: elasticsearch-data

- name: Create elasticsearch data directory
  ansible.builtin.file:
    path: /opt/elasticsearch/
    state: directory
    mode: '0774'

- name: Symbolic link to elasticsearch data directory from docker volume
  ansible.builtin.file:
    src: /var/lib/docker/volumes/elasticsearch-data/_data
    dest: /opt/elasticsearch/data
    state: link
